### ISSUE TITLE
Apakah Ini Open Source?

### ISSUE THREAD

**Issue by AdiCahyaSaputra** [miniph/.github#1]
Project besar kah ini ? Mau nanya ke discord lupa username lu bang wkwkwk

Klo open source ingfokan bang, pen coba kontribusi :v

**Comment by syahid-dev** [comment]
> Project besar kah ini
Nggak, ini cuma buat latihan soalnya kalo ngoding gak pakai AI ngerasa lambat :)

> Mau nanya ke discord lupa username lu bang wkwkwk
Udah di DM ya wkwk

Open source kok ini 😄
